define([], function() {
  return {
    "userLang": "EN",
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "altImgLogo":"Logo of",
    "seeAll" : "See all",
    "seeAllLabel": "See all of my communities",
    "seeAllToggle": "This webpart is for the see all page",
    "seeAllOn" :"Yes",
    "seeAllOff" : "No",
    "setPageNum": "Number per page",
    "setLayoutOpt": "Layout option",
    "setSortOpt" : "sort option",
    "gridIcon" : "Grid",
    "compactIcon" : "Compact",
    "listIcon" : "List",
    "alphabetical": "Alphabetical",
    "dateCreation" : "Creation date",
    "loadingState" : "Loading",
    "ListIcon" : "List",
    "pagePrev" : "Previous",
    "pageNext" : "Next",
    "groups" : "Group",
    "addCommLink": "Link for create a community",
    "commLink": "Modify create a community title",
    "createComm": "Create a community",
    "noResults": "Sorry.\n We couldn't find the community you were looking for.\n Either the community does not exist, or it has a different name.\n Try searching for the community by another letter in the title \n or start your own community.",
    "members": "Members",
    "siteViews": "Site views",
    "created": "Created",
    "lastModified": "Last modified"

  }
});
