define([], function() {
  return {
    "userLang": "FR",
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "altImgLogo": "Logo de",
    "pagPrev": "Précédant",
    "pagNext": "Suivant",
    "setPageNum": "Nombre par page",
    "setLayoutOpt": "Option de mise en page",
    "setSortOpt": "Option de tri",
    "gridIcon": "Grille",
    "compactIcon": "Compacte",
    "dateCreation": "Date de création",
    "alphabetical": "Alphabétique",
    "showmore": "Montrer plus",
    "showless": "Montrer moins",
    "groups": "collectivités",
    "seeAll": "Afficher tout",
    "seeAllLabel": "Afficher toutes mes collectivités",
    "ListIcon": "Liste",
    "seeAllToggle": "Ce webpart est pour la page Afficher tout",
    "seeAllOn": "Oui",
    "seeAllOff": "Non",
    "loadingState": "Chargement en cours",
    "addCommLink": "Lien pour créer une collectivité",
    "commLink": "Modifier créez une collectivité titre",
    "createComm": "Créez une collectivité",
    "noResultsFR": "Aucun collectivité trouvé",
    "members": "Membres",
    "siteViews": "Visites",
    "created": "Créé",
    "lastModified": "Dernière modification"
  }
});
